# Create `.csv` Files

In [1]:
import pandas as pd
import py4macro

In [2]:
df = py4macro.data('pwt')
df.columns

Index(['countrycode', 'country', 'oecd', 'income_group', 'region', 'continent',
       'year', 'rgdpe', 'rgdpo', 'pop', 'emp', 'avh', 'hc', 'ccon', 'cda',
       'cgdpe', 'cgdpo', 'cn', 'ck', 'ctfp', 'cwtfp', 'rgdpna', 'rconna',
       'rdana', 'rnna', 'rkna', 'rtfpna', 'rwtfpna', 'labsh', 'irr', 'delta',
       'xr', 'pl_con', 'pl_da', 'pl_gdpo', 'i_cig', 'i_xm', 'i_xr',
       'i_outlier', 'i_irr', 'cor_exp', 'statcap', 'csh_c', 'csh_i', 'csh_g',
       'csh_x', 'csh_m', 'csh_r', 'pl_c', 'pl_i', 'pl_g', 'pl_x', 'pl_m',
       'pl_n', 'pl_k'],
      dtype='object')

In [3]:
df['year'].unique()

array([1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
       1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019])

## `data1.csv`

In [4]:
cols = ['country', 'cgdpo', 'csh_c', 'csh_i', 'csh_g', 'csh_x', 'csh_m', 'pop', 'continent']
cond = df['year']==2019
df = df.loc[cond,cols]
# df.head()

In [5]:
df['continent'].unique()

array(['North America', 'Africa', 'Europe', 'Asia', 'South America',
       'Australia'], dtype=object)

In [6]:
for continent in df['continent'].unique():
    cond = ( df['continent']==continent )
    print('='*5, continent, '='*20)
    print(df.loc[cond,'country'].unique())

===== North America ====================
['Aruba' 'Anguilla' 'Antigua and Barbuda' 'Bahamas' 'Belize' 'Bermuda'
 'Barbados' 'Canada' 'Costa Rica' 'Curaçao' 'Cayman Islands' 'Dominica'
 'Dominican Republic' 'Grenada' 'Guatemala' 'Honduras' 'Haiti' 'Jamaica'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Mexico' 'Montserrat' 'Nicaragua'
 'Panama' 'El Salvador' 'Sint Maarten (Dutch part)'
 'Turks and Caicos Islands' 'Trinidad and Tobago' 'United States'
 'St. Vincent and the Grenadines' 'British Virgin Islands']
===== Africa ====================
['Angola' 'Burundi' 'Benin' 'Burkina Faso' 'Botswana'
 'Central African Republic' "Côte d'Ivoire" 'Cameroon' 'D.R. of the Congo'
 'Congo' 'Comoros' 'Cabo Verde' 'Djibouti' 'Algeria' 'Egypt' 'Ethiopia'
 'Gabon' 'Ghana' 'Guinea' 'Gambia' 'Guinea-Bissau' 'Equatorial Guinea'
 'Kenya' 'Liberia' 'Lesotho' 'Morocco' 'Madagascar' 'Mali' 'Mozambique'
 'Mauritania' 'Mauritius' 'Malawi' 'Namibia' 'Niger' 'Nigeria' 'Rwanda'
 'Sudan' 'Senegal' 'Sierra Leone' 'Sao Tome and Principe' 'Eswatini'
 'Seychelles' 'Chad' 'Togo' 'Tunisia' 'U.R. of Tanzania: Mainland'
 'Uganda' 'South Africa' 'Zambia' 'Zimbabwe']
===== Europe ====================
['Albania' 'Austria' 'Belgium' 'Bulgaria' 'Bosnia and Herzegovina'
 'Belarus' 'Switzerland' 'Czech Republic' 'Germany' 'Denmark' 'Spain'
 'Estonia' 'Finland' 'France' 'United Kingdom' 'Greece' 'Croatia'
 'Hungary' 'Ireland' 'Iceland' 'Italy' 'Lithuania' 'Luxembourg' 'Latvia'
 'Republic of Moldova' 'North Macedonia' 'Malta' 'Montenegro'
 'Netherlands' 'Norway' 'Poland' 'Portugal' 'Romania' 'Russian Federation'
 'Serbia' 'Slovakia' 'Slovenia' 'Sweden' 'Ukraine']
===== Asia ====================
['United Arab Emirates' 'Armenia' 'Azerbaijan' 'Bangladesh' 'Bahrain'
 'Brunei Darussalam' 'Bhutan' 'China' 'Cyprus' 'Georgia'
 'China, Hong Kong SAR' 'Indonesia' 'India' 'Iran (Islamic Republic of)'
 'Iraq' 'Israel' 'Jordan' 'Japan' 'Kazakhstan' 'Kyrgyzstan' 'Cambodia'
 'Republic of Korea' 'Kuwait' "Lao People's DR" 'Lebanon' 'Sri Lanka'
 'China, Macao SAR' 'Maldives' 'Myanmar' 'Mongolia' 'Malaysia' 'Nepal'
 'Oman' 'Pakistan' 'Philippines' 'State of Palestine' 'Qatar'
 'Saudi Arabia' 'Singapore' 'Syrian Arab Republic' 'Thailand' 'Tajikistan'
 'Turkmenistan' 'Turkey' 'Taiwan' 'Uzbekistan' 'Viet Nam' 'Yemen']
===== South America ====================
['Argentina' 'Bolivia (Plurinational State of)' 'Brazil' 'Chile'
 'Colombia' 'Ecuador' 'Guyana' 'Peru' 'Paraguay' 'Suriname' 'Uruguay'
 'Venezuela (Bolivarian Republic of)']
===== Australia ====================
['Australia' 'Fiji' 'New Zealand']

In [8]:
countries = ['China', 'France', 'India', 'Italy', 'Japan', 'Germany',
             'Republic of Korea', 'Singapore', 'Taiwan', 'United Kingdom',
             'United States']
cond = df['country'].isin(countries)
df = df.loc[cond,:].reset_index(drop=True)
df

,country,cgdpo,csh_c,csh_i,csh_g,csh_x,csh_m,pop,continent
0,China,2.011808e+07,0.387516,0.454168,0.137686,0.192402,-0.167672,1433.783686,Asia
1,Germany,4.274168e+06,0.536769,0.227068,0.183425,0.603715,-0.550977,83.517045,Europe
2,France,2.950146e+06,0.541662,0.273326,0.215368,0.274841,-0.327385,67.351247,Europe
3,United Kingdom,2.994406e+06,0.608676,0.246945,0.197729,0.227445,-0.346071,67.530172,Europe
4,India,9.142121e+06,0.649357,0.270331,0.073454,0.051035,-0.077878,1366.417754,Asia
5,Italy,2.462820e+06,0.577943,0.249250,0.157024,0.307117,-0.292341,60.550075,Europe
6,Japan,5.031850e+06,0.531638,0.246010,0.216620,0.190841,-0.190701,126.860301,Asia
7,Republic of Korea,2.156917e+06,0.436924,0.326824,0.172640,0.466232,-0.403080,51.225308,Asia
8,Singapore,4.771836e+05,0.368542,0.282087,0.112743,1.149431,-1.117445,5.804337,Asia
9,Taiwan,1.100433e+06,0.551436,0.209927,0.175201,0.511099,-0.447663,23.596027,Asia
10,United States,2.056603e+07,0.703201,0.221594,0.114955,0.111490,-0.165832,329.064917,North America

In [9]:
df.loc[3,'country'] = 'UK'
df.loc[7,'country'] = 'Korea'
df.loc[10,'country'] = 'US'
# df

In [10]:
df['con'] = df['cgdpo']*df['csh_c']
df['inv'] = df['cgdpo']*df['csh_i']
df['gov'] = df['cgdpo']*df['csh_g']
df['netx'] = df['cgdpo']*df['csh_x']-df['cgdpo']*df['csh_m']

In [11]:
df = df.rename({'cgdpo':'gdp'}, axis='columns')

In [12]:
cols = ['country','gdp', 'con', 'inv', 'pop', 'continent']
df = df.loc[:,cols]
# df.head()

In [13]:
for col in ['gdp', 'con', 'inv']:
    df[col] = df[col]/1000

# df.head()

In [14]:
for col in df.columns[1:-1]:
    df[col] = round(df[col]).astype(int)

# df.head()

In [15]:
df = df.sort_values('country').reset_index(drop=True)
# df

In [20]:
df.loc[8,'inv'] = None
df.loc[9,'con'] = None
df.loc[9,'inv'] = None
df

      country    gdp      con     inv   pop      continent
0       China  20118   7796.0  9137.0  1434           Asia
1      France   2950   1598.0   806.0    67         Europe
2     Germany   4274   2294.0   971.0    84         Europe
3       India   9142   5936.0  2471.0  1366           Asia
4       Italy   2463   1423.0   614.0    61         Europe
5       Japan   5032   2675.0  1238.0   127           Asia
6       Korea   2157    942.0   705.0    51           Asia
7   Singapore    477    176.0   135.0     6           Asia
8      Taiwan   1100    607.0     NaN    24           Asia
9          UK   2994      NaN     NaN    68         Europe
10         US  20566  14462.0  4557.0   329  North America

In [18]:
cond = (df['country']!='US')
df.loc[cond,:].to_csv('data1.csv', index=False)

In [19]:
pd.read_csv('data1.csv')

     country    gdp     con     inv   pop continent
0      China  20118  7796.0  9137.0  1434      Asia
1     France   2950  1598.0   806.0    67    Europe
2    Germany   4274  2294.0   971.0    84    Europe
3      India   9142  5936.0  2471.0  1366      Asia
4      Italy   2463  1423.0   614.0    61    Europe
5      Japan   5032  2675.0  1238.0   127      Asia
6      Korea   2157   942.0   705.0    51      Asia
7  Singapore    477   176.0   135.0     6      Asia
8     Taiwan   1100   607.0     NaN    24      Asia
9         UK   2994     NaN     NaN    68    Europe

## `data2.csv`

In [60]:
jp = py4macro.data('jpn-q')
jp.head()

,gdp,consumption,investment,government,exports,imports,capital,employed,unemployed,unemployment_rate,hours,total_hours,inflation,price,deflator
,,,,,,,,,,,,,,,
1980-03-31,269747.5,153290.7,65029.2,73039.5,18383.8,24278.8,834219.7,5506.000000,107.666667,1.900000,124.7,686598.200000,5.766667,71.015699,91.2
1980-06-30,268521.8,153551.9,65316.6,72164.5,18631.4,25454.5,843000.2,5525.666667,110.000000,1.966667,124.8,689603.200000,8.166667,72.907806,93.4
1980-09-30,274183.1,155580.0,65765.9,72663.8,18449.3,23885.7,854753.4,5561.333333,116.000000,2.033333,124.0,689605.333333,8.200000,73.898630,94.4
1980-12-31,279601.8,156162.4,66017.5,74761.1,19705.4,23716.5,868241.2,5551.333333,123.333333,2.166667,123.9,687810.200000,8.100000,74.771830,95.4
1981-03-31,281995.7,156757.7,66259.0,76127.6,20289.5,24174.1,879629.9,5568.666667,124.333333,2.200000,123.7,688844.066667,6.833333,75.694271,95.6

In [61]:
cols = ['gdp','consumption','investment','government','exports','imports']
jp = jp.loc[:,cols]

In [62]:
jp = jp.resample('YS').mean()

In [63]:
jp.index = jp.index.year

In [64]:
jp.head()

             gdp  consumption  investment  government    exports    imports

1980  273013.550   154646.250   65532.300   73157.225  18792.475  24333.875
1981  284969.900   158808.175   66388.475   76621.300  21306.600  24911.500
1982  294373.775   166161.650   66669.725   78150.400  21641.975  24771.475
1983  305008.225   171781.900   66873.825   80395.650  22682.975  23952.175
1984  318504.700   177033.050   70091.275   82525.500  26161.050  26511.800

In [65]:
jp.index

Index([1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021],
      dtype='int32', name='')

In [66]:
jp = jp.loc[2012:,:]

In [69]:
jp.columns = ['gdp', 'con', 'inv', 'gov', 'exports', 'imports']
jp

             gdp         con         inv         gov     exports     imports

2012  517928.400  295751.750   98682.200  127135.975   82495.175   86436.950
2013  528522.025  303606.600  100590.050  129984.100   83137.225   89144.075
2014  529656.425  300593.375  103200.725  131434.275   90894.225   96371.300
2015  538098.750  300107.925  108697.000  132249.450   93825.225   96780.800
2016  541964.600  298675.925  109195.975  134433.625   95285.725   95626.275
2017  551205.775  301894.650  111970.275  134762.325  101606.125   98805.700
2018  554349.275  302496.325  113151.350  136011.050  105431.475  102529.750
2019  553019.775  300927.225  113488.750  138450.375  103912.775  103630.950
2020  527946.300  285155.350  104932.325  142151.400   91563.650   96165.275
2021  536811.775  288895.200  103434.900  143454.975  102358.475  101136.150

In [70]:
jp['net_ex'] = jp['exports']-jp['imports']

In [74]:
cols = ['gdp', 'con', 'inv', 'gov', 'net_ex']
jp = jp.loc[:,cols]
jp = jp.reset_index()
jp

                gdp         con         inv         gov    net_ex
0  2012  517928.400  295751.750   98682.200  127135.975 -3941.775
1  2013  528522.025  303606.600  100590.050  129984.100 -6006.850
2  2014  529656.425  300593.375  103200.725  131434.275 -5477.075
3  2015  538098.750  300107.925  108697.000  132249.450 -2955.575
4  2016  541964.600  298675.925  109195.975  134433.625  -340.550
5  2017  551205.775  301894.650  111970.275  134762.325  2800.425
6  2018  554349.275  302496.325  113151.350  136011.050  2901.725
7  2019  553019.775  300927.225  113488.750  138450.375   281.825
8  2020  527946.300  285155.350  104932.325  142151.400 -4601.625
9  2021  536811.775  288895.200  103434.900  143454.975  1222.325

In [75]:
jp = jp.rename({'':'year'}, axis='columns')
jp

   year         gdp         con         inv         gov    net_ex
0  2012  517928.400  295751.750   98682.200  127135.975 -3941.775
1  2013  528522.025  303606.600  100590.050  129984.100 -6006.850
2  2014  529656.425  300593.375  103200.725  131434.275 -5477.075
3  2015  538098.750  300107.925  108697.000  132249.450 -2955.575
4  2016  541964.600  298675.925  109195.975  134433.625  -340.550
5  2017  551205.775  301894.650  111970.275  134762.325  2800.425
6  2018  554349.275  302496.325  113151.350  136011.050  2901.725
7  2019  553019.775  300927.225  113488.750  138450.375   281.825
8  2020  527946.300  285155.350  104932.325  142151.400 -4601.625
9  2021  536811.775  288895.200  103434.900  143454.975  1222.325

In [76]:
jp.to_csv('data2.csv', index=False)

In [77]:
pd.read_csv('data2.csv')

   year         gdp         con         inv         gov    net_ex
0  2012  517928.400  295751.750   98682.200  127135.975 -3941.775
1  2013  528522.025  303606.600  100590.050  129984.100 -6006.850
2  2014  529656.425  300593.375  103200.725  131434.275 -5477.075
3  2015  538098.750  300107.925  108697.000  132249.450 -2955.575
4  2016  541964.600  298675.925  109195.975  134433.625  -340.550
5  2017  551205.775  301894.650  111970.275  134762.325  2800.425
6  2018  554349.275  302496.325  113151.350  136011.050  2901.725
7  2019  553019.775  300927.225  113488.750  138450.375   281.825
8  2020  527946.300  285155.350  104932.325  142151.400 -4601.625
9  2021  536811.775  288895.200  103434.900  143454.975  1222.325